### ISSUE TITLE
회원가입 로직 수정

### ISSUE THREAD

**Issue by baebae02** [ALOC-UOS/aloc-backend#62]
- [ ] 회원가입 시 COURSE를 선택하도록 수정
- [x] 회원가입 시 해당 코스에 맞는 그동안의 Problem을 UserProblem에 Insert 하도록 수정
- [ ] 회원가입 시 백준에서 푼 문제와 userProblem을 비교하여 isSolved 업데이트

**Comment by soonga00** [comment]
회원가입 시 백준에서 푼 문제를 모두 불러와서 비교하는 로직을 고민하였으나, 백준에서 푼문제 로딩 시, 정해진 개수 만큼 불러오고 다음 페이지 조회하기가 어려워
시간이 걸리더라도 문제번호로 검색하고 시간을 확인하는 방식으로 즉, 기존 로직대로 수정없이 진행하는 것이 어떨지 제안 드립니다!
